#!/usr/bin/env node
/*
 * encode-fonts.mjs
 * Closes: F-Wave8-PDF-FONT-EMBED-01
 *
 * Reads the brand .ttf files under supabase/functions/pdf-worker/fonts/ and
 * emits a TypeScript module that exports them as base64 string literals.
 * The pdf-worker bundles these strings directly so no Deno file I/O or HTTP
 * fetch is needed at render time (the Vitest harness for the worker uses a
 * shim that does not have Deno.readFile and we keep the runtime byte-identical
 * between the Vitest harness and the deployed Edge Function).
 *
 * Run after replacing one of the .ttf files:
 *
 *   node scripts/encode-fonts.mjs
 *
 * Commit both the .ttf files and the regenerated fonts.ts.
 *
 * Zero top-level deps. Targets Node 20+ as a .mjs ESM file.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const fontsDir = resolve(root, 'supabase/functions/pdf-worker/fonts');
const outputPath = resolve(root, 'supabase/functions/pdf-worker/fonts.ts');

const FONTS = [
  { file: 'BebasNeue.ttf', constName: 'BEBAS_NEUE_BASE64', label: 'Bebas Neue (display)' },
  { file: 'InterTight.ttf', constName: 'INTER_TIGHT_BASE64', label: 'Inter Tight (body)' },
];

function encodeFont(file) {
  const bytes = readFileSync(resolve(fontsDir, file));
  return bytes.toString('base64');
}

const generatedAt = new Date().toISOString().slice(0, 10);

const lines = [
  '// Generated by scripts/encode-fonts.mjs. Do not edit by hand.',
  '//',
  '// Closes: F-Wave8-PDF-FONT-EMBED-01',
  '//',
  '// Brand fonts embedded as base64 strings so the pdf-worker can register',
  '// them via jsPDF addFileToVFS + addFont without any Deno file I/O or HTTP',
  '// fetch at render time. License: SIL Open Font License 1.1 for both fonts',
  '// (see supabase/functions/pdf-worker/fonts/LICENSE.txt).',
  '//',
  `// Regenerated: ${generatedAt}`,
  '',
];

for (const { file, constName, label } of FONTS) {
  const base64 = encodeFont(file);
  lines.push(`// ${label}. Source file: fonts/${file} (${base64.length} base64 chars).`);
  lines.push(`export const ${constName} = '${base64}';`);
  lines.push('');
}

writeFileSync(outputPath, lines.join('\n'), 'utf8');

const totalBytes = FONTS.reduce(
  (acc, { file }) => acc + readFileSync(resolve(fontsDir, file)).length,
  0,
);
console.log(
  `Wrote ${outputPath} (${FONTS.length} fonts, ${totalBytes} raw bytes).`,
);
