-- ============================================================================
-- Migration: 0111_revoke_authenticated_execute_on_fsm_action_rpcs.sql
-- Wave: 12
-- Phase: RPC-grant hardening. The state-changing action and transition RPCs
--   were granted EXECUTE to BOTH authenticated and service_role at their
--   defining migrations. The SPA never calls any RPC directly (zero .rpc() in
--   apps/web/src); every action RPC is invoked from an Edge Function through
--   admin() (the service_role client). The authenticated grant is therefore an
--   unused attack surface: a hand-rolled PostgREST POST to /rest/v1/rpc/<fn>
--   from an authenticated session could reach these SECURITY DEFINER functions
--   and attempt to bypass the Edge requireCap gate or spoof p_caller_org_id.
--   This migration revokes EXECUTE FROM authenticated on those RPCs only.
--   service_role retains EXECUTE, so the Edge call path is unchanged. The two
--   RLS-context helpers (current_org_id, current_user_role) and every
--   recompute/seed/audit helper KEEP their authenticated grant and are out of
--   scope here (see DOWN MIGRATION note and the closeout for rationale).
-- Closes: F-Wave12-WMS-FSM-RPC-GRANT-HARDEN-01
-- Date: 2026-06-15
--
-- DOWN MIGRATION (operator-only):
--   To restore the prior grant for any function below, re-run the matching:
--     grant execute on function public.<fn>(<sig>) to authenticated;
--   No data is touched; this is a privilege-only change and is fully
--   reversible by re-granting. Do NOT edit this file after apply; write a new
--   forward migration if a re-grant is ever needed.
--
-- Constitutional alignment:
--   - Permission-only change. No table, column, index, trigger, RLS policy,
--     money helper, idempotency table, or audit_log DDL is touched.
--   - RLS is unaffected: the helpers RLS policies evaluate inline as the
--     authenticated user (current_org_id, current_user_role) are NOT revoked.
--   - Edge is unaffected: every target is called via admin() (service_role),
--     which retains EXECUTE.
--   - Idempotent: revoke is naturally idempotent (revoking an absent grant is a
--     no-op and does not error). Safe to re-apply.
--   - No security-invoker caller and no RLS policy references any target RPC;
--     all 18 targets are SECURITY DEFINER and called only from the Edge layer.
-- ============================================================================

-- Job Runs FSM (0098). Edge: three-pl-api via admin().rpc.
revoke execute on function public.start_job_run(uuid, uuid, uuid) from authenticated;
revoke execute on function public.complete_job_run(uuid, uuid, uuid) from authenticated;
revoke execute on function public.close_job_run(uuid, uuid, uuid) from authenticated;
revoke execute on function public.cancel_job_run(uuid, uuid, uuid) from authenticated;

-- Job Run daily log post (0099). Edge: three-pl-api via admin().rpc.
revoke execute on function public.post_job_run_daily_log(uuid, uuid, uuid) from authenticated;

-- Supply Plans FSM (0096, 0101). Edge: three-pl-api via admin().rpc.
revoke execute on function public.release_supply_plan(uuid, uuid, uuid) from authenticated;
revoke execute on function public.cancel_supply_plan(uuid, uuid, uuid) from authenticated;
revoke execute on function public.fulfill_supply_plan(uuid, uuid, uuid) from authenticated;

-- Billing Reviews FSM (0102). Edge: three-pl-api via admin().rpc.
revoke execute on function public.approve_billing_review(uuid, uuid, uuid, text) from authenticated;
revoke execute on function public.cancel_billing_review(uuid, uuid, uuid) from authenticated;

-- Putaway Tasks FSM (0109). Edge: wms-api via admin().rpc.
revoke execute on function public.start_putaway_task(uuid, uuid, uuid) from authenticated;
revoke execute on function public.complete_putaway_task(uuid, uuid, uuid) from authenticated;
revoke execute on function public.cancel_putaway_task(uuid, uuid, uuid) from authenticated;

-- Lot quarantine FSM (0110). Edge: wms-api via admin().rpc.
revoke execute on function public.quarantine_lot(uuid, uuid, uuid) from authenticated;

-- Finance action RPCs (0022, 0023). Edge: finance-api via admin().rpc.
revoke execute on function public.post_journal_entry(uuid) from authenticated;
revoke execute on function public.close_period(uuid, integer, integer) from authenticated;
revoke execute on function public.reopen_period(uuid, integer, integer) from authenticated;

-- Quote -> Project conversion (0041, cross-tenant-hardened). Edge: quotes-api
-- via admin().rpc.
revoke execute on function public.convert_quote_to_project(uuid, uuid, uuid, text) from authenticated;
