-- ============================================================================
-- Migration: 0112_index_unindexed_foreign_keys.sql
-- Wave: 13
-- Phase: A. Performance hardening. The Supabase performance advisor flagged 101
--   foreign-key constraints whose referencing column(s) have no covering index.
--   An unindexed FK forces a sequential scan on the child table for every
--   parent DELETE or UPDATE (the constraint check) and for every join or
--   filter on the FK column. As row counts grow this is the single largest
--   avoidable read cost in the schema. This migration adds one btree index per
--   flagged FK, named idx_<table>_<column>, derived directly from the Postgres
--   catalog (pg_constraint contype='f' with no index whose leading columns
--   match conkey). All 101 flagged FKs are single-column. Pure additive: no
--   table, column, RLS policy, trigger, money helper, idempotency table, or
--   audit_log DDL is touched. Indexes only speed reads and constraint checks;
--   they never change query results, so no edge or SPA change is required.
-- Closes: R-W13-PERF-01
-- Date: 2026-06-15
--
-- DOWN MIGRATION (operator-only):
--   To remove every index this migration adds, run the matching DROP for each
--   index below. No data is touched; an index is derived structure and is fully
--   rebuildable from the base table. Do NOT edit this file after apply; write a
--   new forward migration if a drop is ever needed.
--     drop index if exists public.idx_account_service_definitions_account_id;
--     drop index if exists public.idx_bin_stock_levels_lot_id;
--     drop index if exists public.idx_bom_items_org_id;
--     drop index if exists public.idx_chart_of_accounts_parent_account_id;
--     drop index if exists public.idx_comments_parent_id;
--     drop index if exists public.idx_credit_notes_source_invoice_id;
--     drop index if exists public.idx_customer_pricing_overrides_currency_code;
--     drop index if exists public.idx_exchange_rates_quote_currency_code;
--     drop index if exists public.idx_expenses_expense_category_id;
--     drop index if exists public.idx_expenses_vendor_id;
--     drop index if exists public.idx_fulfillments_sales_order_id;
--     drop index if exists public.idx_fulfillments_shipment_id;
--     drop index if exists public.idx_fulfillments_warehouse_id;
--     drop index if exists public.idx_idempotency_keys_org_id;
--     drop index if exists public.idx_identity_providers_sso_connection_id;
--     drop index if exists public.idx_invoice_versions_org_id;
--     drop index if exists public.idx_invoices_project_id;
--     drop index if exists public.idx_invoices_quote_id;
--     drop index if exists public.idx_item_categories_parent_id;
--     drop index if exists public.idx_items_category_id;
--     drop index if exists public.idx_items_currency_code;
--     drop index if exists public.idx_items_default_tax_id;
--     drop index if exists public.idx_items_unit_id;
--     drop index if exists public.idx_job_run_daily_log_consumed_line_items_job_run_daily_log_id;
--     drop index if exists public.idx_job_run_daily_log_produced_line_items_job_run_daily_log_id;
--     drop index if exists public.idx_job_run_daily_logs_job_run_id;
--     drop index if exists public.idx_job_template_lines_template_id;
--     drop index if exists public.idx_job_templates_default_bom_item_id;
--     drop index if exists public.idx_journal_entries_reversal_of_id;
--     drop index if exists public.idx_kitting_job_consumed_line_items_kitting_job_id;
--     drop index if exists public.idx_kitting_job_produced_line_items_kitting_job_id;
--     drop index if exists public.idx_kitting_jobs_sales_order_id;
--     drop index if exists public.idx_kitting_jobs_warehouse_id;
--     drop index if exists public.idx_leads_converted_customer_id;
--     drop index if exists public.idx_leads_converted_opportunity_id;
--     drop index if exists public.idx_lots_item_id;
--     drop index if exists public.idx_manufacturing_run_consumed_line_items_manufacturing_run_id;
--     drop index if exists public.idx_manufacturing_run_produced_line_items_manufacturing_run_id;
--     drop index if exists public.idx_manufacturing_runs_warehouse_id;
--     drop index if exists public.idx_opportunities_customer_id;
--     drop index if exists public.idx_opportunities_lead_id;
--     drop index if exists public.idx_org_memberships_role_id;
--     drop index if exists public.idx_payments_customer_id;
--     drop index if exists public.idx_production_runs_warehouse_id;
--     drop index if exists public.idx_project_line_items_item_id;
--     drop index if exists public.idx_project_line_items_tax_rate_id;
--     drop index if exists public.idx_projects_currency_code;
--     drop index if exists public.idx_projects_customer_id;
--     drop index if exists public.idx_projects_job_type_id;
--     drop index if exists public.idx_projects_source_job_template_id;
--     drop index if exists public.idx_putaway_tasks_item_id;
--     drop index if exists public.idx_putaway_tasks_lot_id;
--     drop index if exists public.idx_putaway_tasks_warehouse_id;
--     drop index if exists public.idx_quote_line_items_item_id;
--     drop index if exists public.idx_quote_line_items_tax_id;
--     drop index if exists public.idx_quote_line_items_vas_id;
--     drop index if exists public.idx_quote_templates_default_currency_code;
--     drop index if exists public.idx_quote_templates_default_payment_method_id;
--     drop index if exists public.idx_quote_templates_default_tax_id;
--     drop index if exists public.idx_quotes_currency_code;
--     drop index if exists public.idx_quotes_customer_id;
--     drop index if exists public.idx_quotes_default_tax_id;
--     drop index if exists public.idx_quotes_job_type_id;
--     drop index if exists public.idx_quotes_payment_method_id;
--     drop index if exists public.idx_quotes_pricing_tier_id;
--     drop index if exists public.idx_quotes_source_job_template_id;
--     drop index if exists public.idx_receiving_order_line_items_lot_id;
--     drop index if exists public.idx_receiving_order_line_items_receiving_order_id;
--     drop index if exists public.idx_receiving_orders_dock_location_id;
--     drop index if exists public.idx_receiving_orders_purchase_order_id;
--     drop index if exists public.idx_receiving_orders_vendor_id;
--     drop index if exists public.idx_receiving_orders_warehouse_id;
--     drop index if exists public.idx_sales_order_line_items_sales_order_id;
--     drop index if exists public.idx_sales_orders_channel_id;
--     drop index if exists public.idx_sales_orders_customer_id;
--     drop index if exists public.idx_sales_orders_project_id;
--     drop index if exists public.idx_shifts_member_id;
--     drop index if exists public.idx_shifts_team_id;
--     drop index if exists public.idx_shifts_warehouse_id;
--     drop index if exists public.idx_shipment_line_items_shipment_id;
--     drop index if exists public.idx_shipments_warehouse_id;
--     drop index if exists public.idx_sso_connections_default_role_code;
--     drop index if exists public.idx_stock_movements_location_id;
--     drop index if exists public.idx_stock_movements_lot_id;
--     drop index if exists public.idx_supply_plan_lines_resolved_po_id;
--     drop index if exists public.idx_supply_plan_lines_resolved_receiving_order_id;
--     drop index if exists public.idx_supply_plan_lines_supply_plan_id;
--     drop index if exists public.idx_three_pl_accounts_customer_id;
--     drop index if exists public.idx_time_entries_assignment_id;
--     drop index if exists public.idx_time_entries_member_id;
--     drop index if exists public.idx_time_entries_shift_id;
--     drop index if exists public.idx_value_added_services_currency_code;
--     drop index if exists public.idx_value_added_services_default_tax_id;
--     drop index if exists public.idx_vendor_bills_purchase_order_id;
--     drop index if exists public.idx_warehouse_locations_parent_location_id;
--     drop index if exists public.idx_warehouse_locations_warehouse_id;
--     drop index if exists public.idx_work_assignments_member_id;
--     drop index if exists public.idx_work_assignments_shift_id;
--     drop index if exists public.idx_workforce_members_user_id;
--     drop index if exists public.idx_workforce_team_members_member_id;
--     drop index if exists public.idx_workforce_team_members_team_id;
--
-- Constitutional alignment:
--   - Pure additive index DDL. No table, column, RLS policy, trigger, function,
--     money helper (_cents), idempotency table, or audit_log object is created,
--     altered, or dropped. No money or idempotency or audit invariant is in
--     scope.
--   - Idempotent: every statement uses CREATE INDEX IF NOT EXISTS, so the
--     migration is safe to re-apply and is a no-op against an already-indexed
--     column.
--   - Forward-only: this is a new numbered file; no prior migration is edited.
--   - RLS is unaffected. Indexes change neither row visibility nor result sets;
--     they only accelerate the FK constraint check and FK-column joins/filters.
--   - The full list of indexes is derived from the live Postgres catalog
--     (pg_constraint contype='f' with no covering index on conkey), not hand
--     enumerated. All 101 flagged FKs are single-column.
-- ============================================================================

create index if not exists idx_account_service_definitions_account_id on public.account_service_definitions (account_id);
create index if not exists idx_bin_stock_levels_lot_id on public.bin_stock_levels (lot_id);
create index if not exists idx_bom_items_org_id on public.bom_items (org_id);
create index if not exists idx_chart_of_accounts_parent_account_id on public.chart_of_accounts (parent_account_id);
create index if not exists idx_comments_parent_id on public.comments (parent_id);
create index if not exists idx_credit_notes_source_invoice_id on public.credit_notes (source_invoice_id);
create index if not exists idx_customer_pricing_overrides_currency_code on public.customer_pricing_overrides (currency_code);
create index if not exists idx_exchange_rates_quote_currency_code on public.exchange_rates (quote_currency_code);
create index if not exists idx_expenses_expense_category_id on public.expenses (expense_category_id);
create index if not exists idx_expenses_vendor_id on public.expenses (vendor_id);
create index if not exists idx_fulfillments_sales_order_id on public.fulfillments (sales_order_id);
create index if not exists idx_fulfillments_shipment_id on public.fulfillments (shipment_id);
create index if not exists idx_fulfillments_warehouse_id on public.fulfillments (warehouse_id);
create index if not exists idx_idempotency_keys_org_id on public.idempotency_keys (org_id);
create index if not exists idx_identity_providers_sso_connection_id on public.identity_providers (sso_connection_id);
create index if not exists idx_invoice_versions_org_id on public.invoice_versions (org_id);
create index if not exists idx_invoices_project_id on public.invoices (project_id);
create index if not exists idx_invoices_quote_id on public.invoices (quote_id);
create index if not exists idx_item_categories_parent_id on public.item_categories (parent_id);
create index if not exists idx_items_category_id on public.items (category_id);
create index if not exists idx_items_currency_code on public.items (currency_code);
create index if not exists idx_items_default_tax_id on public.items (default_tax_id);
create index if not exists idx_items_unit_id on public.items (unit_id);
create index if not exists idx_job_run_daily_log_consumed_line_items_job_run_daily_log_id on public.job_run_daily_log_consumed_line_items (job_run_daily_log_id);
create index if not exists idx_job_run_daily_log_produced_line_items_job_run_daily_log_id on public.job_run_daily_log_produced_line_items (job_run_daily_log_id);
create index if not exists idx_job_run_daily_logs_job_run_id on public.job_run_daily_logs (job_run_id);
create index if not exists idx_job_template_lines_template_id on public.job_template_lines (template_id);
create index if not exists idx_job_templates_default_bom_item_id on public.job_templates (default_bom_item_id);
create index if not exists idx_journal_entries_reversal_of_id on public.journal_entries (reversal_of_id);
create index if not exists idx_kitting_job_consumed_line_items_kitting_job_id on public.kitting_job_consumed_line_items (kitting_job_id);
create index if not exists idx_kitting_job_produced_line_items_kitting_job_id on public.kitting_job_produced_line_items (kitting_job_id);
create index if not exists idx_kitting_jobs_sales_order_id on public.kitting_jobs (sales_order_id);
create index if not exists idx_kitting_jobs_warehouse_id on public.kitting_jobs (warehouse_id);
create index if not exists idx_leads_converted_customer_id on public.leads (converted_customer_id);
create index if not exists idx_leads_converted_opportunity_id on public.leads (converted_opportunity_id);
create index if not exists idx_lots_item_id on public.lots (item_id);
create index if not exists idx_manufacturing_run_consumed_line_items_manufacturing_run_id on public.manufacturing_run_consumed_line_items (manufacturing_run_id);
create index if not exists idx_manufacturing_run_produced_line_items_manufacturing_run_id on public.manufacturing_run_produced_line_items (manufacturing_run_id);
create index if not exists idx_manufacturing_runs_warehouse_id on public.manufacturing_runs (warehouse_id);
create index if not exists idx_opportunities_customer_id on public.opportunities (customer_id);
create index if not exists idx_opportunities_lead_id on public.opportunities (lead_id);
create index if not exists idx_org_memberships_role_id on public.org_memberships (role_id);
create index if not exists idx_payments_customer_id on public.payments (customer_id);
create index if not exists idx_production_runs_warehouse_id on public.production_runs (warehouse_id);
create index if not exists idx_project_line_items_item_id on public.project_line_items (item_id);
create index if not exists idx_project_line_items_tax_rate_id on public.project_line_items (tax_rate_id);
create index if not exists idx_projects_currency_code on public.projects (currency_code);
create index if not exists idx_projects_customer_id on public.projects (customer_id);
create index if not exists idx_projects_job_type_id on public.projects (job_type_id);
create index if not exists idx_projects_source_job_template_id on public.projects (source_job_template_id);
create index if not exists idx_putaway_tasks_item_id on public.putaway_tasks (item_id);
create index if not exists idx_putaway_tasks_lot_id on public.putaway_tasks (lot_id);
create index if not exists idx_putaway_tasks_warehouse_id on public.putaway_tasks (warehouse_id);
create index if not exists idx_quote_line_items_item_id on public.quote_line_items (item_id);
create index if not exists idx_quote_line_items_tax_id on public.quote_line_items (tax_id);
create index if not exists idx_quote_line_items_vas_id on public.quote_line_items (vas_id);
create index if not exists idx_quote_templates_default_currency_code on public.quote_templates (default_currency_code);
create index if not exists idx_quote_templates_default_payment_method_id on public.quote_templates (default_payment_method_id);
create index if not exists idx_quote_templates_default_tax_id on public.quote_templates (default_tax_id);
create index if not exists idx_quotes_currency_code on public.quotes (currency_code);
create index if not exists idx_quotes_customer_id on public.quotes (customer_id);
create index if not exists idx_quotes_default_tax_id on public.quotes (default_tax_id);
create index if not exists idx_quotes_job_type_id on public.quotes (job_type_id);
create index if not exists idx_quotes_payment_method_id on public.quotes (payment_method_id);
create index if not exists idx_quotes_pricing_tier_id on public.quotes (pricing_tier_id);
create index if not exists idx_quotes_source_job_template_id on public.quotes (source_job_template_id);
create index if not exists idx_receiving_order_line_items_lot_id on public.receiving_order_line_items (lot_id);
create index if not exists idx_receiving_order_line_items_receiving_order_id on public.receiving_order_line_items (receiving_order_id);
create index if not exists idx_receiving_orders_dock_location_id on public.receiving_orders (dock_location_id);
create index if not exists idx_receiving_orders_purchase_order_id on public.receiving_orders (purchase_order_id);
create index if not exists idx_receiving_orders_vendor_id on public.receiving_orders (vendor_id);
create index if not exists idx_receiving_orders_warehouse_id on public.receiving_orders (warehouse_id);
create index if not exists idx_sales_order_line_items_sales_order_id on public.sales_order_line_items (sales_order_id);
create index if not exists idx_sales_orders_channel_id on public.sales_orders (channel_id);
create index if not exists idx_sales_orders_customer_id on public.sales_orders (customer_id);
create index if not exists idx_sales_orders_project_id on public.sales_orders (project_id);
create index if not exists idx_shifts_member_id on public.shifts (member_id);
create index if not exists idx_shifts_team_id on public.shifts (team_id);
create index if not exists idx_shifts_warehouse_id on public.shifts (warehouse_id);
create index if not exists idx_shipment_line_items_shipment_id on public.shipment_line_items (shipment_id);
create index if not exists idx_shipments_warehouse_id on public.shipments (warehouse_id);
create index if not exists idx_sso_connections_default_role_code on public.sso_connections (default_role_code);
create index if not exists idx_stock_movements_location_id on public.stock_movements (location_id);
create index if not exists idx_stock_movements_lot_id on public.stock_movements (lot_id);
create index if not exists idx_supply_plan_lines_resolved_po_id on public.supply_plan_lines (resolved_po_id);
create index if not exists idx_supply_plan_lines_resolved_receiving_order_id on public.supply_plan_lines (resolved_receiving_order_id);
create index if not exists idx_supply_plan_lines_supply_plan_id on public.supply_plan_lines (supply_plan_id);
create index if not exists idx_three_pl_accounts_customer_id on public.three_pl_accounts (customer_id);
create index if not exists idx_time_entries_assignment_id on public.time_entries (assignment_id);
create index if not exists idx_time_entries_member_id on public.time_entries (member_id);
create index if not exists idx_time_entries_shift_id on public.time_entries (shift_id);
create index if not exists idx_value_added_services_currency_code on public.value_added_services (currency_code);
create index if not exists idx_value_added_services_default_tax_id on public.value_added_services (default_tax_id);
create index if not exists idx_vendor_bills_purchase_order_id on public.vendor_bills (purchase_order_id);
create index if not exists idx_warehouse_locations_parent_location_id on public.warehouse_locations (parent_location_id);
create index if not exists idx_warehouse_locations_warehouse_id on public.warehouse_locations (warehouse_id);
create index if not exists idx_work_assignments_member_id on public.work_assignments (member_id);
create index if not exists idx_work_assignments_shift_id on public.work_assignments (shift_id);
create index if not exists idx_workforce_members_user_id on public.workforce_members (user_id);
create index if not exists idx_workforce_team_members_member_id on public.workforce_team_members (member_id);
create index if not exists idx_workforce_team_members_team_id on public.workforce_team_members (team_id);
