-- ============================================================================
-- Migration: 0113_function_search_path_and_anon_execute_hardening.sql
-- Wave: 13
-- Phase: A. Function hardening. Two Supabase security-advisor findings are
--   closed here against schema public:
--   (1) function_search_path_mutable (37 functions): every function whose
--       search_path is not pinned is exposed to search-path-injection. A role
--       that can create objects in a schema earlier on the resolution path
--       could shadow an unqualified name the function body references and run
--       attacker-controlled code under the function. The 37 are the 36
--       trg_*_set_updated_at trigger functions plus the kitstak_audit_canonical
--       JSON-normaliser helper. We pin each to `SET search_path = public` via
--       ALTER FUNCTION. No body is rewritten and no behaviour changes; this is
--       a resolution-context change only. (The SECURITY DEFINER action RPCs and
--       the SECURITY DEFINER trigger functions already pin search_path and are
--       not in scope.)
--   (2) anon_security_definer_function_executable (11 functions): SECURITY
--       DEFINER functions in the exposed API schema are reachable by the anon
--       role. Ten are SECURITY DEFINER trigger functions (Postgres rejects a
--       direct RPC call to a trigger function, so the practical surface is the
--       revoke being defence in depth) and the eleventh, resolve_org_by_host,
--       is the host-to-org resolver. resolve_org_by_host is invoked from the
--       Edge layer via admin() (service_role); the public pre-auth host-resolve
--       path runs through the tenants-api Edge Function (verify_jwt = false),
--       not through a direct anon /rest/v1/rpc call. Revoking EXECUTE from
--       public and anon on all 11 closes the finding without affecting the Edge
--       call path. anon inherits the default PUBLIC execute grant, so PUBLIC must
--       be revoked too, not anon alone; resolve_org_by_host keeps its explicit
--       authenticated and service_role grants.
--   service_role and authenticated grants are left untouched: every legitimate
--   caller is service_role (Edge admin()) or the Postgres trigger machinery,
--   neither of which is the anon role. This mirrors the revoke pattern in
--   migration 0111.
-- Closes: R-W13-SEC-02
-- Date: 2026-06-15
--
-- DOWN MIGRATION (operator-only):
--   search_path pin reversal (per function below):
--     alter function public.<fn>(<sig>) reset search_path;
--   anon EXECUTE re-grant reversal (per function below):
--     grant execute on function public.<fn>(<sig>) to public;
--   No data is touched; both changes are configuration/privilege-only and are
--   fully reversible. Do NOT edit this file after apply; write a new forward
--   migration if a reset or re-grant is ever needed.
--
-- Constitutional alignment:
--   - Configuration and privilege-only change. No table, column, index,
--     trigger definition, RLS policy, money helper, idempotency table, or
--     audit_log DDL is touched. No function body is rewritten.
--   - RLS is unaffected: the RLS-context helpers (current_org_id,
--     current_user_role) are not in either list and keep their grants.
--   - Edge is unaffected: resolve_org_by_host is called via admin()
--     (service_role), which retains EXECUTE. The trigger functions fire from
--     the Postgres trigger machinery, not from a role grant.
--   - Idempotent: ALTER FUNCTION ... SET search_path is a CREATE-OR-REPLACE
--     style attribute write (re-applying sets the same value), and REVOKE is
--     naturally idempotent (revoking an absent grant is a no-op and does not
--     error). Safe to re-apply.
--   - All 37 + 11 targets were enumerated from pg_proc against the live schema
--     (exact argument signatures below) so ALTER/REVOKE resolve unambiguously.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- (1) Pin search_path = public on the 37 search-path-mutable functions.
-- ----------------------------------------------------------------------------

-- Canonical-JSON normaliser used by the audit hash chain (0001 family).
alter function public.kitstak_audit_canonical(jsonb) set search_path = public;

-- updated_at touch triggers (one per table, no arguments).
alter function public.trg_account_service_definitions_set_updated_at() set search_path = public;
alter function public.trg_billing_reviews_set_updated_at() set search_path = public;
alter function public.trg_fulfillments_set_updated_at() set search_path = public;
alter function public.trg_invoices_set_updated_at() set search_path = public;
alter function public.trg_job_run_daily_log_consumed_line_items_set_updated_at() set search_path = public;
alter function public.trg_job_run_daily_log_produced_line_items_set_updated_at() set search_path = public;
alter function public.trg_job_run_daily_logs_set_updated_at() set search_path = public;
alter function public.trg_job_runs_set_updated_at() set search_path = public;
alter function public.trg_job_template_lines_set_updated_at() set search_path = public;
alter function public.trg_job_templates_set_updated_at() set search_path = public;
alter function public.trg_journal_entries_set_updated_at() set search_path = public;
alter function public.trg_kitting_job_consumed_line_items_set_updated_at() set search_path = public;
alter function public.trg_kitting_job_produced_line_items_set_updated_at() set search_path = public;
alter function public.trg_kitting_jobs_set_updated_at() set search_path = public;
alter function public.trg_lots_set_updated_at() set search_path = public;
alter function public.trg_manufacturing_run_consumed_line_items_set_updated_at() set search_path = public;
alter function public.trg_manufacturing_run_produced_line_items_set_updated_at() set search_path = public;
alter function public.trg_manufacturing_runs_set_updated_at() set search_path = public;
alter function public.trg_period_close_set_updated_at() set search_path = public;
alter function public.trg_project_line_items_set_updated_at() set search_path = public;
alter function public.trg_putaway_tasks_set_updated_at() set search_path = public;
alter function public.trg_receiving_order_line_items_set_updated_at() set search_path = public;
alter function public.trg_sales_channels_set_updated_at() set search_path = public;
alter function public.trg_sales_order_line_items_set_updated_at() set search_path = public;
alter function public.trg_sales_orders_set_updated_at() set search_path = public;
alter function public.trg_shifts_set_updated_at() set search_path = public;
alter function public.trg_shipment_line_items_set_updated_at() set search_path = public;
alter function public.trg_supply_plan_lines_set_updated_at() set search_path = public;
alter function public.trg_supply_plans_set_updated_at() set search_path = public;
alter function public.trg_three_pl_accounts_set_updated_at() set search_path = public;
alter function public.trg_time_entries_set_updated_at() set search_path = public;
alter function public.trg_warehouse_locations_set_updated_at() set search_path = public;
alter function public.trg_work_assignments_set_updated_at() set search_path = public;
alter function public.trg_workforce_members_set_updated_at() set search_path = public;
alter function public.trg_workforce_team_members_set_updated_at() set search_path = public;
alter function public.trg_workforce_teams_set_updated_at() set search_path = public;

-- ----------------------------------------------------------------------------
-- (2) Revoke EXECUTE from anon on the 11 anon-executable SECURITY DEFINER
--     functions. Host resolver (called by tenants-api / Edge admin()).
-- ----------------------------------------------------------------------------
revoke execute on function public.resolve_org_by_host(text) from public, anon;

-- SECURITY DEFINER trigger functions (fire from the trigger machinery, never
-- from public, anon; revoke is defence in depth). Finance JE + audit-state + recompute
-- + project-stamp triggers.
revoke execute on function public.trg_credit_note_allocations_je() from public, anon;
revoke execute on function public.trg_credit_note_allocations_recompute() from public, anon;
revoke execute on function public.trg_credit_note_audit_state_change() from public, anon;
revoke execute on function public.trg_invoice_audit_state_change() from public, anon;
revoke execute on function public.trg_invoices_je_on_send() from public, anon;
revoke execute on function public.trg_je_audit_state_change() from public, anon;
revoke execute on function public.trg_payment_allocations_recompute() from public, anon;
revoke execute on function public.trg_payments_je_on_create() from public, anon;
revoke execute on function public.trg_stamp_project_initial() from public, anon;
revoke execute on function public.trg_stamp_project_phase_initial() from public, anon;
