-- ============================================================================
-- Migration: 0114_putaway_complete_requires_destination.sql
-- Wave: 13
-- Phase: A. WMS putaway hardening. The 0109 complete_putaway_task RPC gated the
--   stock_movements insert on `if v_actual_location_id is not null then`, so
--   completing a task whose actual_location_id was NULL marked it 'done' while
--   posting ZERO movements: a silent null-destination no-op that lost the stock
--   move. This migration makes the destination MANDATORY at complete: a complete
--   with no actual_location_id now RAISES (STATE_CONFLICT) instead of marking the
--   task done with no ledger effect. It also adds set_putaway_destination so the
--   operator can set the bin before completing, the natural pairing for the new
--   guard.
-- Closes: R-W13-WMS-01
-- Date: 2026-06-15
--
-- DOWN MIGRATION (operator-only; not auto-run):
--   Restore the prior complete_putaway_task body (the 0109 version, which made
--   the movement emission conditional on actual_location_id and treated a null
--   destination as a status-only no-op) and drop the new action RPC:
--
--     drop function if exists public.set_putaway_destination(uuid, uuid, uuid, uuid);
--
--     create or replace function public.complete_putaway_task(
--       p_putaway_task_id uuid, p_actor uuid, p_caller_org_id uuid
--     ) returns uuid language plpgsql security definer set search_path = public as $$
--     declare
--       v_org_id uuid; v_status text; v_warehouse_id uuid; v_item_id uuid;
--       v_quantity numeric(18,4); v_source_location_id uuid;
--       v_actual_location_id uuid; v_lot_id uuid;
--     begin
--       select org_id, status, warehouse_id, item_id, quantity,
--              source_location_id, actual_location_id, lot_id
--         into v_org_id, v_status, v_warehouse_id, v_item_id, v_quantity,
--              v_source_location_id, v_actual_location_id, v_lot_id
--         from public.putaway_tasks where id = p_putaway_task_id for update;
--       if v_org_id is null or v_org_id <> p_caller_org_id then
--         raise exception 'NOT_FOUND: putaway task not found' using errcode = 'P0001';
--       end if;
--       if v_status = 'done' then return p_putaway_task_id; end if;
--       if v_status <> 'in_progress' then
--         raise exception 'STATE_CONFLICT: putaway task not in in_progress state (was %)', v_status
--           using errcode = 'P0001';
--       end if;
--       update public.putaway_tasks
--          set status = 'done', completed_at = now(), updated_by = p_actor
--        where id = p_putaway_task_id;
--       if v_actual_location_id is not null then
--         insert into public.stock_movements (
--           org_id, warehouse_id, item_id, location_id, lot_id,
--           movement_type, quantity, unit_cost_cents,
--           source_entity_type, source_entity_id, occurred_at, created_by
--         ) values (
--           v_org_id, v_warehouse_id, v_item_id, v_source_location_id, v_lot_id,
--           'transfer_out', v_quantity, 0, 'putaway_task', p_putaway_task_id,
--           now(), p_actor
--         ), (
--           v_org_id, v_warehouse_id, v_item_id, v_actual_location_id, v_lot_id,
--           'transfer_in', v_quantity, 0, 'putaway_task', p_putaway_task_id,
--           now(), p_actor
--         );
--       end if;
--       return p_putaway_task_id;
--     end; $$;
--
--   Forward-only is the constitutional path. Do NOT edit this file after apply;
--   write a new forward migration if the decision is ever reversed.
--
-- Constitutional alignment:
--   RLS rules          No table, policy, or RLS change. The two RPCs are
--                      SECURITY DEFINER and 3-arg / 4-arg cross-tenant: they read
--                      the task's org from the row and surface a cross-tenant or
--                      missing task as NOT_FOUND (never 403), matching the 0109
--                      transition RPCs.
--   Money rules        No _cents column change. The emitted transfer movements
--                      keep unit_cost_cents = 0 (a relocation, not a revaluation);
--                      the paired transfer_out / transfer_in net to zero at the
--                      warehouse grain. No monetary math here.
--   Audit rules        No audit_log DDL. The status transition to 'done' still
--                      fires the 0109 trg_audit_putaway_tasks trigger; the
--                      emitted stock_movements remain the append-only ledger
--                      record. set_putaway_destination is a plain UPDATE on a
--                      non-status field (actual_location_id), so the audit trigger
--                      records it with the status unchanged (from_state =
--                      to_state), the existing rich-FSM behaviour for non-status
--                      edits.
--   Ledger model       complete_putaway_task stays a warehouse-flat internal move
--                      (transfer_out at the source dock + transfer_in at the
--                      destination bin, same quantity, 0030 signed-CASE nets to
--                      zero at the warehouse grain while the 0107 AFTER INSERT
--                      recompute shifts the bin grain). The ONLY behaviour change:
--                      a null destination no longer skips the move silently; it
--                      raises STATE_CONFLICT before marking the task done, so a
--                      done task ALWAYS has its paired movements.
--   Idempotency        Unchanged. complete_putaway_task keeps its for-update row
--                      lock and the already-'done' early return, so a retried
--                      complete never double-emits; the
--                      stock_movements_putaway_task_uniq backstop index (0109)
--                      still guarantees at most one transfer_out / transfer_in per
--                      task. The new STATE_CONFLICT raise fires only when the task
--                      is still in_progress with no destination, so it never
--                      interferes with the idempotent done path.
--                      set_putaway_destination is a plain idempotent UPDATE (the
--                      Edge handler-table Idempotency-Key contract is unchanged).
--   Migration rules    Forward-only. CREATE OR REPLACE for complete_putaway_task;
--                      a new CREATE OR REPLACE for set_putaway_destination. Does
--                      not edit any numbered file. All DDL idempotent.
--   State machine      complete_putaway_task keeps the in_progress -> done
--                      transition with the NOT_FOUND / not-in_progress guards.
--                      set_putaway_destination is NOT a status transition: it sets
--                      the destination bin while the task is still 'pending'
--                      ('suggested') or 'in_progress' (rejecting a done /
--                      cancelled task with STATE_CONFLICT), so the operator can
--                      set or correct the bin before completing.
--   Grants             Both RPCs mirror the 0109 + 0111 posture: revoke from
--                      public / anon, grant to service_role, and (per 0111, since
--                      these are action RPCs called only via the Edge service_role
--                      client) revoke EXECUTE from authenticated. The CREATE OR
--                      REPLACE on complete_putaway_task would re-establish the old
--                      authenticated grant from its body's defaults if not
--                      re-revoked; this migration re-revokes it so the 0111
--                      hardening is preserved.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- complete_putaway_task: same 3-arg signature, same in_progress -> done
-- transition and idempotent done early-return, but a NULL destination now
-- RAISES STATE_CONFLICT before the task is marked done (no more silent
-- zero-movement no-op). When a destination IS set it behaves exactly as 0109:
-- mark done, then emit the warehouse-flat transfer_out / transfer_in pair
-- (unit_cost_cents 0), letting the 0107 AFTER INSERT recompute shift the bin
-- stock while the warehouse total stays flat.
-- ---------------------------------------------------------------------------

create or replace function public.complete_putaway_task(
  p_putaway_task_id uuid,
  p_actor uuid,
  p_caller_org_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_status text;
  v_warehouse_id uuid;
  v_item_id uuid;
  v_quantity numeric(18,4);
  v_source_location_id uuid;
  v_actual_location_id uuid;
  v_lot_id uuid;
begin
  -- Row lock (for update): serialises concurrent completes on this task. The
  -- second transaction blocks here until the first commits, then re-reads
  -- status = 'done' below and returns idempotently, so the transfer_out /
  -- transfer_in pair is emitted exactly once. The
  -- stock_movements_putaway_task_uniq partial unique index is the DB-enforced
  -- backstop if a lock is ever bypassed.
  select org_id, status, warehouse_id, item_id, quantity,
         source_location_id, actual_location_id, lot_id
    into v_org_id, v_status, v_warehouse_id, v_item_id, v_quantity,
         v_source_location_id, v_actual_location_id, v_lot_id
    from public.putaway_tasks where id = p_putaway_task_id for update;

  if v_org_id is null or v_org_id <> p_caller_org_id then
    raise exception 'NOT_FOUND: putaway task not found' using errcode = 'P0001';
  end if;

  if v_status = 'done' then
    return p_putaway_task_id; -- idempotent: a retried complete never double-emits
  end if;
  if v_status <> 'in_progress' then
    raise exception 'STATE_CONFLICT: putaway task not in in_progress state (was %)', v_status
      using errcode = 'P0001';
  end if;

  -- A complete REQUIRES a destination bin. Without one there is no bin to stow
  -- the stock in, so completing would emit zero movements and silently lose the
  -- move (the 0109 bug). Raise BEFORE marking the task done so the task stays
  -- in_progress and the operator can set the destination (set_putaway_destination)
  -- and complete again. STATE_CONFLICT, errcode P0001, mapped to 409 by the Edge.
  if v_actual_location_id is null then
    raise exception 'STATE_CONFLICT: putaway requires a destination bin'
      using errcode = 'P0001';
  end if;

  update public.putaway_tasks
     set status = 'done', completed_at = now(), updated_by = p_actor
   where id = p_putaway_task_id;

  -- Warehouse-flat internal move. The 0107 AFTER INSERT trigger fires the
  -- warehouse + bin recomputes per row; do not call recompute directly.
  -- unit_cost_cents = 0: a relocation, not a revaluation. transfer_out at the
  -- source dock and transfer_in at the destination bin net to zero at the
  -- warehouse grain (0030 signed-CASE), so the warehouse total stays flat while
  -- the bin grain shifts the quantity. When v_source_location_id is NULL the
  -- transfer_out is a no-bin reduction (warehouse -qty, no bin row), still
  -- warehouse-flat against the transfer_in.
  insert into public.stock_movements (
    org_id, warehouse_id, item_id,
    location_id, lot_id,
    movement_type, quantity, unit_cost_cents,
    source_entity_type, source_entity_id,
    occurred_at, created_by
  ) values (
    v_org_id, v_warehouse_id, v_item_id,
    v_source_location_id, v_lot_id,
    'transfer_out', v_quantity, 0,
    'putaway_task', p_putaway_task_id,
    now(), p_actor
  ), (
    v_org_id, v_warehouse_id, v_item_id,
    v_actual_location_id, v_lot_id,
    'transfer_in', v_quantity, 0,
    'putaway_task', p_putaway_task_id,
    now(), p_actor
  );

  return p_putaway_task_id;
end;
$$;

revoke execute on function public.complete_putaway_task(uuid, uuid, uuid) from public, anon;
grant execute on function public.complete_putaway_task(uuid, uuid, uuid) to service_role;
-- Preserve the 0111 hardening: action RPCs are called only via the Edge
-- service_role client, so authenticated must NOT retain EXECUTE. The CREATE OR
-- REPLACE above re-runs the 0109 grants whose body defaults would otherwise
-- restore the authenticated grant; re-revoke it here.
revoke execute on function public.complete_putaway_task(uuid, uuid, uuid) from authenticated;

comment on function public.complete_putaway_task(uuid, uuid, uuid) is
  'Completes a putaway task (Wave 13 / R-W13-WMS-01): in_progress -> done, stamps completed_at, THEN emits the warehouse-flat internal move. 3-arg cross-tenant guard (NOT_FOUND). Idempotent on an already-done task (no double emit). A NULL actual_location_id now RAISES STATE_CONFLICT before the task is marked done (no more silent zero-movement no-op): set the destination via set_putaway_destination first. When a destination is set it inserts transfer_out at source_location_id and transfer_in at actual_location_id (same quantity, unit_cost_cents 0), netting to zero at the warehouse grain while the 0107 bin recompute shifts the bin stock.';

-- ---------------------------------------------------------------------------
-- set_putaway_destination: set (or correct) the destination bin on a still-open
-- task. 4-arg cross-tenant pattern: reads the task's org from the row, NOT_FOUND
-- on a cross-tenant or missing task (never 403). Allowed only while the task is
-- pending ('suggested') or in_progress; a done / cancelled task STATE_CONFLICTs
-- (its destination is frozen). Sets actual_location_id and updated_by; the 0109
-- updated_at trigger stamps updated_at. Status-only-adjacent: this is a plain
-- field UPDATE, NOT a status transition. The Edge layer validates the bin lives
-- in the task's warehouse before calling this (assertLocationInWarehouse).
-- ---------------------------------------------------------------------------

create or replace function public.set_putaway_destination(
  p_putaway_task_id uuid,
  p_actual_location_id uuid,
  p_actor uuid,
  p_caller_org_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_status text;
begin
  -- Row lock (for update): serialises a concurrent set / complete on this task.
  select org_id, status into v_org_id, v_status
    from public.putaway_tasks where id = p_putaway_task_id for update;

  if v_org_id is null or v_org_id <> p_caller_org_id then
    raise exception 'NOT_FOUND: putaway task not found' using errcode = 'P0001';
  end if;

  -- Only a still-open task can take a destination. A done task has already
  -- posted its movements against a frozen destination; a cancelled task never
  -- will. status 'suggested' is the 0109 'pending' equivalent (the FSM names the
  -- initial state 'suggested').
  if v_status not in ('suggested', 'in_progress') then
    raise exception 'STATE_CONFLICT: putaway destination cannot be set (was %)', v_status
      using errcode = 'P0001';
  end if;

  update public.putaway_tasks
     set actual_location_id = p_actual_location_id, updated_by = p_actor
   where id = p_putaway_task_id;

  return p_putaway_task_id;
end;
$$;

revoke execute on function public.set_putaway_destination(uuid, uuid, uuid, uuid) from public, anon;
grant execute on function public.set_putaway_destination(uuid, uuid, uuid, uuid) to service_role;
-- Action RPC, called only via the Edge service_role client: authenticated never
-- gets EXECUTE (the 0111 posture for action RPCs).
revoke execute on function public.set_putaway_destination(uuid, uuid, uuid, uuid) from authenticated;

comment on function public.set_putaway_destination(uuid, uuid, uuid, uuid) is
  'Sets (or corrects) the destination bin (actual_location_id) on a still-open putaway task (Wave 13 / R-W13-WMS-01). 4-arg cross-tenant guard (NOT_FOUND). Allowed only while status is suggested or in_progress; a done or cancelled task STATE_CONFLICTs. Plain field UPDATE, not a status transition. Pairs with the new complete_putaway_task rule that a NULL destination raises STATE_CONFLICT. The Edge validates the bin lives in the task warehouse before calling.';
