-- ============================================================================
-- Migration: 0115_item_master_fields.sql
-- Wave: 13
-- Phase: B. Catalog deepening. The item master (0012) carries SKU, name,
--   pricing, and a structured unit FK (unit_id) plus unit_cost_cents. The
--   3PL/WMS commercial layer needs a few additional operator-facing catalog
--   attributes that do not justify their own tables: a free-text unit of
--   measure label, a reorder point threshold, a barcode/UPC string, and a
--   distinct purchasing cost field. These are additive, nullable, and do not
--   alter any existing column. unit_of_measure is a denormalized label that
--   complements (does not replace) the existing unit_id FK; cost_cents is a
--   second money attribute alongside unit_cost_cents, kept separate so the new
--   catalog cost surface does not overload the existing landed-cost column.
-- Closes: R-W13-CAT-01
-- Date: 2026-06-15
--
-- DOWN MIGRATION (operator-only):
--   To reverse this migration, drop the four added columns from public.items:
--     alter table public.items drop column if exists barcode;
--     alter table public.items drop column if exists reorder_point;
--     alter table public.items drop column if exists cost_cents;
--     alter table public.items drop column if exists unit_of_measure;
--   All four are nullable with no default, so the drop is data-preserving for
--   every other column. Not auto-run. Do NOT edit this file after apply; write
--   a new forward migration if a change is ever needed.
--
-- Constitutional alignment:
--   - Additive only. Four nullable columns ADDED to an existing table. No
--     column is dropped, renamed, or retyped; no backfill; no NOT NULL.
--   - Money rules: the cost column is BIGINT and carries the _cents suffix
--     (cost_cents). A non-negative CHECK mirrors unit_price_cents/
--     unit_cost_cents so storage stays in integer cents.
--   - RLS unaffected: public.items already has Pattern A RLS (0012) covering
--     all columns. No policy DDL here, no RLS surface touched.
--   - Idempotent: every ADD COLUMN uses IF NOT EXISTS; safe to re-apply.
--   - No idempotency table, audit_log, trigger, or money-helper DDL is touched.
-- ============================================================================

alter table public.items
  add column if not exists unit_of_measure text;

alter table public.items
  add column if not exists cost_cents bigint
    check (cost_cents is null or cost_cents >= 0);

alter table public.items
  add column if not exists reorder_point numeric
    check (reorder_point is null or reorder_point >= 0);

alter table public.items
  add column if not exists barcode text;
