-- ============================================================================
-- Migration: 0117_revoke_authenticated_execute_remaining_security_definer.sql
-- Wave: 13
-- Phase: RPC-grant hardening, follow-on to 0111. Closes the remainder the
--   security advisor flags as authenticated_security_definer_function_executable.
--   0111 revoked the FSM action/transition RPCs from authenticated and
--   explicitly left the recompute/seed/audit helpers and the audit/numbering/
--   conversion service RPCs in scope for a follow-up; this is that follow-up.
--   Supabase's stock ALTER DEFAULT PRIVILEGES grants EXECUTE to anon, authenticated,
--   and service_role on every new public function. The prior hardening migrations
--   revoked anon (and PUBLIC) but left authenticated, so 115 SECURITY DEFINER
--   functions still carry a direct authenticated=X grant. The SPA never calls any
--   RPC directly (zero .rpc() in apps/web/src); every one of these is invoked only
--   from an Edge Function through admin() (the service_role client), or fires as a
--   trigger (trigger execution is not gated on the invoker's EXECUTE privilege).
--   The authenticated grant is therefore an unused attack surface. Confirmed live
--   on prod: an authenticated PostgREST POST to /rest/v1/rpc/audit_append_state_change
--   could forge an audit_log row; kitstak_audit_chain_head and verify_audit_chain
--   leak another tenant's hash-chain head by org_id; the recompute_* helpers mutate
--   another tenant's invoice, stock, or project totals by id. This migration revokes
--   EXECUTE FROM authenticated on every SECURITY DEFINER public function still
--   authenticated-executable, EXCEPT the two RLS-context helpers that RLS policies
--   evaluate inline as the authenticated user (current_org_id, current_user_role).
-- Closes: F-Wave13-SEC-AUTH-EXEC-REVIEW-01
-- Date: 2026-06-15
--
-- Targets (115 functions; the DO block re-derives the set from the live catalog
--   so a signature typo cannot silently miss one. Enumerated here for the record):
--   25 directly-callable service RPCs -
--     audit_append_state_change, verify_audit_chain, kitstak_audit_chain_head,
--     check_journal_balance, finance_je_enabled, kitstak_je_account,
--     next_doc_number, reset_numbering_sequence, seed_org_chart_of_accounts,
--     set_default_payment_method, set_default_tax, set_quote_requires_approval,
--     snapshot_quote_version, convert_lead, convert_project_to_invoice,
--     resolve_org_by_host, recompute_invoice_paid, recompute_invoice_totals,
--     recompute_invoice_credit_allocated, recompute_payment_unapplied,
--     recompute_credit_note_applied, recompute_project_totals,
--     recompute_quote_totals, recompute_stock_level, recompute_bin_stock_level.
--   90 trigger functions (tg_*/trg_* plus recompute_purchase_order_totals and
--     recompute_vendor_bill_paid) - no direct-call exploit (a raw RPC errors
--     with no trigger context) but revoked for a clean advisor board.
--
-- DOWN MIGRATION (operator-only):
--   To restore the prior grant for any function, re-run the matching:
--     grant execute on function public.<fn>(<sig>) to authenticated;
--   No data is touched; this is a privilege-only change, fully reversible by
--   re-granting. Do NOT edit this file after apply; write a new forward
--   migration if a re-grant is ever needed.
--
-- Constitutional alignment:
--   - Permission-only change. No table, column, index, trigger, RLS policy,
--     money helper, idempotency table, or audit_log DDL is touched. The
--     audit_log append path is unchanged: audit_append_state_change keeps its
--     service_role grant (the auto-state-transition triggers and Edge writes run
--     as service_role), so legitimate audit writes are unaffected; only the
--     direct authenticated forge path is closed.
--   - RLS is unaffected: current_org_id and current_user_role - the only two
--     functions any RLS policy references (verified: 361 and 261 policy refs; no
--     other target appears in any pg_policy expression) - are explicitly excluded
--     and keep their authenticated grant.
--   - Edge is unaffected: every target is called via admin() (service_role),
--     which retains EXECUTE; trigger functions fire regardless of invoker grant.
--   - Idempotent: revoke is naturally idempotent; the DO block re-derives the
--     target set from the live catalog, so re-applying is a safe no-op.
-- ============================================================================

do $$
declare
  r record;
begin
  for r in
    select p.oid::regprocedure as sig
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prosecdef
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
      and p.proname not in ('current_org_id', 'current_user_role')
  loop
    execute format('revoke execute on function %s from authenticated;', r.sig);
  end loop;
end
$$;
