-- ============================================================================
-- Migration: 0118_sso_oidc_configs_and_provider_validation.sql
-- Wave: 13
-- Phase: SSO MVP (store-metadata). The R-W13-AUTH-01 UI manages the
--   sso_connections record and saml_configs exists from 0002, but there was no
--   place to store OIDC provider metadata and no gate preventing a connection
--   from being activated before its IdP handshake is confirmed. This migration
--   adds (1) provider_validated_at on sso_connections plus a CHECK that a
--   connection cannot be is_active=true until it has been validated, and (2) an
--   oidc_configs child table mirroring saml_configs (same Pattern B RLS, same
--   shape conventions) so the OIDC half of the metadata-store endpoint has a
--   home. The actual Supabase Auth provider handshake stays an operator
--   dashboard step; provider_validated_at is the operator attestation that it
--   is wired, and only then can the connection be activated.
-- Closes: F-Wave13-SSO-HANDSHAKE-01 (MVP store-metadata phase; live assertion
--   auto-provisioning is a later follow-up)
-- Date: 2026-06-15
--
-- SECURITY NOTE: the OIDC client_secret is NOT stored in this MVP. oidc_configs
--   holds only the public OIDC parameters (issuer, endpoints, client_id). The
--   client_secret is collected in the later live-handshake phase, where it goes
--   behind Supabase Vault (F-Wave13-SSO-SECRET-VAULT-01), since nothing performs
--   a token exchange before then. saml_configs.idp_x509_cert is an IdP public
--   signing certificate (not a secret), stored plaintext as before.
--
-- DOWN MIGRATION (operator-only):
--   drop index if exists public.sso_connections_org_all_idx;
--   alter table public.sso_connections
--     drop constraint if exists sso_connections_active_requires_validation;
--   alter table public.sso_connections drop column if exists provider_validated_at;
--   drop table if exists public.oidc_configs;
--   Do NOT edit this file after apply; write a new forward migration instead.
--
-- Constitutional alignment:
--   - RLS: oidc_configs is tenant-scoped via Pattern B (parent join to
--     sso_connections, org_id = current_org_id()), byte-for-byte the saml_configs
--     policy shape from 0116. SELECT is org-scoped; INSERT/UPDATE/DELETE also
--     require org_owner/org_admin. No new global table.
--   - Money/idempotency/audit_log: untouched. Config tables carry no state
--     machine, so (like saml_configs) they register no audit trigger.
--   - Multi-stage: additive only (new nullable column, new constraint, new
--     table). The CHECK is back-filled safe: any already-active connection is
--     stamped validated at its updated_at before the constraint is added, so the
--     constraint can never fail on existing data.
--   - Idempotent: IF NOT EXISTS on column/table; drop-if-exists before every
--     constraint and policy create; re-runnable.
-- ============================================================================

-- 1. provider_validated_at: the operator attestation that the IdP handshake is
--    wired in the Supabase project. Nullable; null means "configured but not
--    yet validated", so the connection cannot be activated.
alter table public.sso_connections
  add column if not exists provider_validated_at timestamptz;

-- 2. Back-fill: an already-active connection was implicitly validated when it
--    was activated, so stamp it before adding the constraint. No-op when there
--    are no active rows.
update public.sso_connections
   set provider_validated_at = updated_at
 where is_active
   and provider_validated_at is null;

-- 3. A connection cannot be active until it has been validated.
alter table public.sso_connections
  drop constraint if exists sso_connections_active_requires_validation;
alter table public.sso_connections
  add constraint sso_connections_active_requires_validation
  check (is_active = false or provider_validated_at is not null);

-- 3b. Non-partial org_id index. The saml_configs / oidc_configs RLS SELECT
--     policies join to sso_connections by org_id; the existing
--     sso_connections_org_idx is partial (WHERE is_active), so it does not cover
--     the pre-activation rows the metadata-store flow reads most.
create index if not exists sso_connections_org_all_idx
  on public.sso_connections (org_id);

-- 4. oidc_configs: the OIDC sibling of saml_configs. One row per connection.
create table if not exists public.oidc_configs (
  sso_connection_id uuid primary key
    references public.sso_connections(id) on delete cascade,
  issuer_url text not null,
  authorization_endpoint text not null,
  token_endpoint text not null,
  userinfo_endpoint text not null,
  client_id text not null,
  scopes jsonb not null default '["openid", "profile", "email"]'::jsonb,
  attribute_mappings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

alter table public.oidc_configs enable row level security;

-- Pattern B RLS, mirroring saml_configs (0116): parent join to sso_connections,
-- org-scoped read, org_owner/org_admin write.
drop policy if exists oidc_configs_select on public.oidc_configs;
create policy oidc_configs_select on public.oidc_configs
  for select to authenticated
  using ((EXISTS ( SELECT 1 FROM sso_connections sc WHERE ((sc.id = oidc_configs.sso_connection_id) AND (sc.org_id = (select current_org_id()))))));

drop policy if exists oidc_configs_insert on public.oidc_configs;
create policy oidc_configs_insert on public.oidc_configs
  for insert to authenticated
  with check ((EXISTS ( SELECT 1 FROM sso_connections sc WHERE ((sc.id = oidc_configs.sso_connection_id) AND (sc.org_id = (select current_org_id())) AND ((select current_user_role()) = ANY (ARRAY['org_owner'::text, 'org_admin'::text]))))));

drop policy if exists oidc_configs_update on public.oidc_configs;
create policy oidc_configs_update on public.oidc_configs
  for update to authenticated
  using ((EXISTS ( SELECT 1 FROM sso_connections sc WHERE ((sc.id = oidc_configs.sso_connection_id) AND (sc.org_id = (select current_org_id())) AND ((select current_user_role()) = ANY (ARRAY['org_owner'::text, 'org_admin'::text]))))))
  with check ((EXISTS ( SELECT 1 FROM sso_connections sc WHERE ((sc.id = oidc_configs.sso_connection_id) AND (sc.org_id = (select current_org_id())) AND ((select current_user_role()) = ANY (ARRAY['org_owner'::text, 'org_admin'::text]))))));

drop policy if exists oidc_configs_delete on public.oidc_configs;
create policy oidc_configs_delete on public.oidc_configs
  for delete to authenticated
  using ((EXISTS ( SELECT 1 FROM sso_connections sc WHERE ((sc.id = oidc_configs.sso_connection_id) AND (sc.org_id = (select current_org_id())) AND ((select current_user_role()) = ANY (ARRAY['org_owner'::text, 'org_admin'::text]))))));
