-- ============================================================================
-- Migration: 0120_item_supply_source.sql
-- Wave: 13
-- Phase: B. Catalog deepening. The item master (0012, extended in 0115) carries
--   no supply-source dimension, so cost roll-ups cannot tell org-owned material
--   from material the org neither owns nor pays for. This adds a supply_source
--   classification to public.items so the catalog, the reference pickers, and
--   the cost roll-ups can distinguish in-house stock, customer-supplied material,
--   vendor-consigned material, and third-party-consigned material.
-- Closes: F-UIUX-ENTITYPICKER-SUPPLY-SOURCE-01
-- Date: 2026-06-17
--
-- DOWN MIGRATION (operator-only):
--   To reverse this migration, drop the added column from public.items:
--     alter table public.items drop column if exists supply_source;
--   The column is NOT NULL with a default, so every other column is preserved by
--   the drop. Not auto-run. Do NOT edit this file after apply; write a new
--   forward migration if a change is ever needed.
--
-- Constitutional alignment:
--   - Additive only. One column ADDED to an existing table. No column is dropped,
--     renamed, or retyped.
--   - House style: a TEXT column with an inline CHECK constraint (the same
--     pattern as items.kind in 0012), not a native Postgres ENUM type.
--   - NOT NULL DEFAULT 'in_house' backfills every existing row to 'in_house' in
--     one statement; no separate backfill pass is needed and no row is left null.
--   - RLS unaffected: public.items already has Pattern A RLS (0012) covering all
--     columns. No policy DDL here, no RLS surface touched.
--   - Money rules: no money column is added or changed. This column is a
--     classification that the cost roll-ups read (0122 and the edge folds); it
--     holds no cents and does no math.
--   - Idempotent: ADD COLUMN IF NOT EXISTS; safe to re-apply.
--   - No idempotency table, audit_log, trigger, or money-helper DDL is touched.
-- ============================================================================

alter table public.items
  add column if not exists supply_source text not null default 'in_house'
    check (supply_source in (
      'in_house',
      'customer_supplied',
      'vendor_consigned',
      'third_party_consigned'
    ));

comment on column public.items.supply_source is
  'Material supply source classification (F-UIUX-ENTITYPICKER-SUPPLY-SOURCE-01). in_house = org-owned stock; customer_supplied = customer owns the material; vendor_consigned = vendor owns it until consumed, the org pays on consumption; third_party_consigned = a third party owns it and the org does not pay for it as material. Cost roll-ups treat customer_supplied and third_party_consigned as zero org material cost; in_house and vendor_consigned carry normal captured cost. Default in_house preserves the pre-migration costing for every existing row.';
