-- ============================================================================
-- Migration: 0121_supply_source_line_overrides.sql
-- Wave: 13
-- Phase: B. Catalog deepening, supply-source per-line override. items.supply_source
--   (0120) is the default for every consumption of that item. Operators need to
--   override the source on an individual line (for example, a normally in-house
--   item supplied by the customer for one job). This adds a nullable supply_source
--   override to the five cost-bearing consumption-line tables. NULL means inherit
--   the item default; a non-null value wins for that line.
-- Closes: F-UIUX-ENTITYPICKER-SUPPLY-SOURCE-01
-- Date: 2026-06-17
--
-- DOWN MIGRATION (operator-only):
--   alter table public.receiving_order_line_items drop column if exists supply_source;
--   alter table public.shipment_line_items drop column if exists supply_source;
--   alter table public.manufacturing_run_consumed_line_items drop column if exists supply_source;
--   alter table public.kitting_job_consumed_line_items drop column if exists supply_source;
--   alter table public.job_run_daily_log_consumed_line_items drop column if exists supply_source;
--   Every column is nullable with no default, so each drop is data-preserving.
--   Not auto-run. Do NOT edit this file after apply; write a new forward
--   migration if a change is ever needed.
--
-- Constitutional alignment:
--   - Additive only. One nullable column ADDED to each of five existing tables.
--     No column is dropped, renamed, or retyped; no backfill; no NOT NULL.
--   - House style: TEXT plus an inline CHECK (null or one of the four values),
--     mirroring items.supply_source (0120). The effective source a roll-up reads
--     is COALESCE(line.supply_source, item.supply_source).
--   - RLS unaffected: all five tables already carry RLS (Pattern B parent-join
--     scope) covering every column. No policy DDL here.
--   - Money rules: no money column is added or changed. This override only
--     classifies a line so the cost roll-ups (0122 and the edge consumed-cost
--     folds) can zero org cost for not-org-owned material.
--   - Idempotent: every ADD COLUMN uses IF NOT EXISTS; safe to re-apply.
--   - No idempotency table, audit_log, trigger, or money-helper DDL is touched.
-- ============================================================================

alter table public.receiving_order_line_items
  add column if not exists supply_source text
    check (supply_source is null or supply_source in (
      'in_house', 'customer_supplied', 'vendor_consigned', 'third_party_consigned'
    ));

alter table public.shipment_line_items
  add column if not exists supply_source text
    check (supply_source is null or supply_source in (
      'in_house', 'customer_supplied', 'vendor_consigned', 'third_party_consigned'
    ));

alter table public.manufacturing_run_consumed_line_items
  add column if not exists supply_source text
    check (supply_source is null or supply_source in (
      'in_house', 'customer_supplied', 'vendor_consigned', 'third_party_consigned'
    ));

alter table public.kitting_job_consumed_line_items
  add column if not exists supply_source text
    check (supply_source is null or supply_source in (
      'in_house', 'customer_supplied', 'vendor_consigned', 'third_party_consigned'
    ));

alter table public.job_run_daily_log_consumed_line_items
  add column if not exists supply_source text
    check (supply_source is null or supply_source in (
      'in_house', 'customer_supplied', 'vendor_consigned', 'third_party_consigned'
    ));
