-- ============================================================================
-- Migration: 0123_search_indexes.sql
-- Wave: 13
-- Phase: C. List indexing (2026-06-17 UI scan, Workstream C). The list toolbar
--   adds server-side free-text search and money/date facets across quotes,
--   invoices, customers, items, projects, and vendors. The org + status/state +
--   customer + created_at btrees already exist (0001 onward); this migration
--   adds the two pieces that do not: pg_trgm trigram GIN indexes so the ILIKE
--   search on number/name/sku/email/phone is index-backed, and a few money/date
--   btrees for the amount sort and the open-balance / overdue facets.
-- Closes: F-UISCAN-LIST-INDEXING-01
-- Date: 2026-06-18
--
-- DOWN MIGRATION (operator-only):
--   To reverse, drop the indexes added below (each is IF EXISTS-safe) and, only
--   if no other object depends on it, the extension:
--     drop index if exists public.quotes_number_trgm_idx;  -- (and the rest below)
--     drop extension if exists pg_trgm;  -- only if nothing else uses trigram
--   Not auto-run. Do NOT edit this file after apply; write a new forward
--   migration if a change is ever needed.
--
-- Constitutional alignment:
--   - Additive only. Creates one extension and read-path indexes. No table,
--     column, type, RLS policy, trigger, function, or data is added, dropped, or
--     changed. Index creation never alters query results, only their speed.
--   - RLS unaffected: every covered table keeps its existing Pattern A/B RLS.
--     The trigram indexes accelerate the ILIKE filter the handlers run AFTER the
--     org-scoped .eq('org_id', ...); they do not widen visibility.
--   - Money rules: no money column is added or changed. The (org_id, total_cents)
--     / (org_id, balance_cents) btrees index existing BIGINT cents columns for
--     sort/filter; they store no value and do no math.
--   - Idempotent: CREATE EXTENSION IF NOT EXISTS, CREATE INDEX IF NOT EXISTS
--     throughout; safe to re-apply.
--   - No idempotency table, audit_log, or money-helper DDL is touched.
--   - Scale note: CREATE INDEX CONCURRENTLY cannot run inside a migration
--     transaction; at current row counts a plain CREATE INDEX is instant. A
--     CONCURRENTLY rebuild is filed as a scale follow-up
--     (F-UISCAN-INDEX-CONCURRENTLY-01).
-- ============================================================================

-- Trigram support for index-backed ILIKE. Installed into the extensions schema
-- per the Supabase house convention (pgcrypto, uuid-ossp live there too).
create extension if not exists pg_trgm with schema extensions;

-- Trigram GIN indexes for the per-list free-text search. Partial on
-- deleted_at IS NULL to match the soft-delete gate every list query applies.
create index if not exists quotes_number_trgm_idx
  on public.quotes using gin (number extensions.gin_trgm_ops)
  where deleted_at is null;
create index if not exists quotes_title_trgm_idx
  on public.quotes using gin (title extensions.gin_trgm_ops)
  where deleted_at is null;

create index if not exists invoices_number_trgm_idx
  on public.invoices using gin (invoice_number extensions.gin_trgm_ops)
  where deleted_at is null;

create index if not exists customers_name_trgm_idx
  on public.customers using gin (display_name extensions.gin_trgm_ops)
  where deleted_at is null;
create index if not exists customers_email_trgm_idx
  on public.customers using gin (primary_email extensions.gin_trgm_ops)
  where deleted_at is null;
create index if not exists customers_phone_trgm_idx
  on public.customers using gin (primary_phone extensions.gin_trgm_ops)
  where deleted_at is null;

create index if not exists items_sku_trgm_idx
  on public.items using gin (sku extensions.gin_trgm_ops)
  where deleted_at is null;
create index if not exists items_name_trgm_idx
  on public.items using gin (name extensions.gin_trgm_ops)
  where deleted_at is null;

create index if not exists projects_number_trgm_idx
  on public.projects using gin (number extensions.gin_trgm_ops)
  where deleted_at is null;
create index if not exists projects_name_trgm_idx
  on public.projects using gin (name extensions.gin_trgm_ops)
  where deleted_at is null;

create index if not exists vendors_name_trgm_idx
  on public.vendors using gin (display_name extensions.gin_trgm_ops)
  where deleted_at is null;

-- Money / date btrees for the amount sort and the open-balance / overdue
-- facets. Org-scoped composite indexes, partial on the soft-delete gate.
create index if not exists quotes_org_total_idx
  on public.quotes (org_id, total_cents)
  where deleted_at is null;

create index if not exists invoices_org_balance_idx
  on public.invoices (org_id, balance_cents)
  where deleted_at is null;
create index if not exists invoices_org_due_idx
  on public.invoices (org_id, due_date)
  where deleted_at is null;

create index if not exists items_org_price_idx
  on public.items (org_id, unit_price_cents)
  where deleted_at is null and is_active;
