-- ============================================================================
-- Migration: 0124_list_experience_flags.sql
-- Wave: 13
-- Phase: C. List experience flag seeding (2026-06-17 UI scan, Workstreams B/C).
--   The shared DetailHeader (feature.detail_header) and the server list toolbar
--   (feature.list_toolbar) are SPA render flags, default off. They must exist as
--   org_feature_flags rows for the operator to see and toggle them on /admin/
--   flags. This migration adds both to seed_org_settings (so new orgs get them)
--   and backfills every existing org (so they are toggleable today). It also
--   closes the noted billing.trial_gate.enabled seed gap (the trial-gate flag was
--   never in seed_org_settings, so it never appeared for toggling on a fresh org).
-- Closes: F-UISCAN-FLAG-SEED-01
-- Date: 2026-06-18
--
-- DOWN MIGRATION (operator-only):
--   To reverse, remove the three flag rows and restore the prior seed list:
--     delete from public.org_feature_flags
--       where flag_key in ('feature.detail_header','feature.list_toolbar',
--                          'billing.trial_gate.enabled');
--     -- then CREATE OR REPLACE seed_org_settings without the three appended keys.
--   Not auto-run. Do NOT edit this file after apply; write a new forward
--   migration if a change is ever needed.
--
-- Constitutional alignment:
--   - Additive only. Appends three flag keys to the seed list and inserts the
--     matching default-off rows. No table, column, type, or RLS policy is added,
--     dropped, or changed.
--   - RLS unaffected: org_feature_flags keeps its existing Pattern A RLS. The
--     backfill runs as the migration (service role) and writes one row per org.
--   - Money rules: no money column or helper is touched. (billing.trial_gate is a
--     gate flag, not a money value.)
--   - The seed_org_settings CREATE OR REPLACE keeps the exact signature, SECURITY
--     DEFINER, and search_path of the live function; only the v_flags array grows
--     by three entries. It is not a money, idempotency, or audit_log helper.
--   - Idempotent: ON CONFLICT DO NOTHING on the backfill; CREATE OR REPLACE on the
--     function. Safe to re-apply.
-- ============================================================================

create or replace function public.seed_org_settings(p_org_id uuid)
  returns integer
  language plpgsql
  security definer
  set search_path to 'public'
as $function$
declare
  v_inserted integer := 0;
  v_flag text;
  v_flags text[] := array[
    'plugins.three_pl',
    'plugins.manufacturing',
    'plugins.copack_ecom',
    'plugins.kitforce',
    'plugins.kitcost',
    'plugins.wms',
    'feature.collaboration',
    'feature.global_search',
    'feature.imports',
    'feature.exports',
    'feature.customer_portal',
    'feature.detail_header',
    'feature.list_toolbar',
    'billing.trial_gate.enabled'
  ];
begin
  if p_org_id is null then
    raise exception 'VALIDATION_ERROR: p_org_id is required' using errcode = '22023';
  end if;

  foreach v_flag in array v_flags loop
    insert into public.org_feature_flags (org_id, flag_key, is_enabled, config)
    values (p_org_id, v_flag, false, '{}'::jsonb)
    on conflict (org_id, flag_key) do nothing;
    if found then
      v_inserted := v_inserted + 1;
    end if;
  end loop;

  return v_inserted;
end;
$function$;

-- Backfill the three flags (default off) for every existing org so they appear
-- on /admin/flags and can be toggled now, not only on the next provisioning.
insert into public.org_feature_flags (org_id, flag_key, is_enabled, config)
select o.id, f.flag_key, false, '{}'::jsonb
from public.organizations o
cross join (
  values
    ('feature.detail_header'),
    ('feature.list_toolbar'),
    ('billing.trial_gate.enabled')
) as f(flag_key)
on conflict (org_id, flag_key) do nothing;
