-- ============================================================================
-- Migration: 0133_revoke_authenticated_execute_quote_flow_rpcs.sql
-- Wave: Quote-flow P2 (security hardening follow-up to 0111 / 0117)
-- Phase: RPC-grant hardening for the two SECURITY DEFINER functions added during
--   the 2026-06-23 quote-flow work. duplicate_quote (0129) and
--   seed_org_default_job_types (0130) were defined with the pre-sweep 0094 grant
--   pattern (EXECUTE to authenticated, service_role), re-introducing a direct
--   authenticated=X grant that the 0111 / 0117 sweep had removed from every other
--   SECURITY DEFINER public function (the post-sweep baseline keeps authenticated
--   EXECUTE only on the two RLS-context helpers current_org_id /
--   current_user_role). The SPA never calls an RPC directly (zero .rpc() in
--   apps/web/src) and the edge invokes both functions via admin() (the
--   service_role client), so the authenticated grant is an unused PostgREST
--   attack surface. Confirmed live on prod (2026-06-23): both carry
--   authenticated=X, anon=- ; an authenticated POST to
--   /rest/v1/rpc/duplicate_quote or /rest/v1/rpc/seed_org_default_job_types with
--   known UUID arguments could trigger an unauthorized cross-org write (clone a
--   quote into, or seed job types into, an org the caller does not belong to).
--   Both are org-gated and take UUID arguments, so there is no data
--   exfiltration; the security advisor rates it WARN
--   (authenticated_security_definer_function_executable). This migration revokes
--   EXECUTE FROM authenticated on both, keeping service_role.
-- Closes: post-quote-flow security advisor follow-up
--   (authenticated_security_definer_function_executable: duplicate_quote 0129,
--   seed_org_default_job_types 0130).
-- Date: 2026-06-23
--
-- DOWN MIGRATION (operator-only; forward-only repo, do not auto-apply):
--   grant execute on function public.duplicate_quote(uuid, uuid, uuid)
--     to authenticated;
--   grant execute on function public.seed_org_default_job_types(uuid)
--     to authenticated;
--   No data is touched; this is a privilege-only change, fully reversible by
--   re-granting. Do NOT edit this file after apply; write a new forward migration
--   if a re-grant is ever needed.
--
-- Constitutional alignment:
--   - Permission-only change. No table, column, index, trigger, RLS policy, money
--     helper, idempotency table, or audit_log DDL is touched. Both function bodies
--     are unchanged; only their EXECUTE grant narrows.
--   - RLS is unaffected: current_org_id and current_user_role (the only two
--     functions any RLS policy references) are not touched and keep their
--     authenticated grant. Both target functions remain org-gated internally
--     (cross-tenant arguments raise NOT_FOUND), so this is defence in depth.
--   - Edge is unaffected: quotes-api (POST /quotes/:id/duplicate) and
--     provision_organization, which also runs seed_org_default_job_types, invoke
--     these via admin() (service_role), which retains EXECUTE.
--   - Idempotent: revoke is naturally idempotent; re-applying is a safe no-op. The
--     signatures are pinned to the live catalog (verified against pg_proc on prod
--     and staging, both at max_migration 0132, 2026-06-23).
--   - Forward-only. No prior migration is edited.
-- ============================================================================

revoke execute on function public.duplicate_quote(uuid, uuid, uuid)
  from authenticated;

revoke execute on function public.seed_org_default_job_types(uuid)
  from authenticated;
